[package]
name = "wrapper"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.1.0", features = ["derive", "clap_derive"]}
which = "4.2.4"