[package]
name = "additions"
version = "0.1.0"
edition = "2018"


[[bin]]
name = "additions"
path = "./src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"