[package]
name = "additions"
version = "0.1.0"
edition = "2018"


[[bin]]
name = "additions"
path = "./src/main.rs"

[dependencies]

# Those need to be set dynamically
#lazy_static = "1.4.0"
#serde = { version = "1.0", features = ["derive"] }