name: Build LaTeX document
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: document.tex
          working_directory: latex
          latexmk_use_lualatex: true
          extra_fonts: |
            fonts/*.ttf
            fonts/*.otf
      - name: Pull PDF
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: document.pdf
